
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Gurnoor Singh Saini\Desktop\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x700")
window.configure(bg = "#1C1C1C")


canvas = Canvas(
    window,
    bg = "#1C1C1C",
    height = 700,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    262.0,
    59.0,
    anchor="nw",
    text="Welcome, Administrator !",
    fill="#FFFFFF",
    font=("ArialRoundedMTBold", 36 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    230.0,
    877.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    934.0,
    59.0,
    966.0,
    98.0,
    fill="#000000",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=261.0,
    y=139.0,
    width=337.0,
    height=69.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=629.0,
    y=138.0,
    width=337.0,
    height=69.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=261.0,
    y=231.0,
    width=337.0,
    height=69.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=629.0,
    y=231.0,
    width=337.0,
    height=69.0
)

canvas.create_rectangle(
    261.0,
    323.0,
    966.0,
    676.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
